<?php
function rudate($format, $timestamp = 0, $nominative_month = false)
{
    if(!$timestamp) $timestamp = time();
    elseif(!preg_match("/^[0-9]+$/", $timestamp)) $timestamp = strtotime($timestamp);

    $F = $nominative_month ? array(1=>"Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь") : array(1=>"Января", "Февраля", "Марта", "Апреля", "Мая", "Июня", "Июля", "Августа", "Сентября", "Октября", "Ноября", "Декабря");
    $M = array(1=>"Янв", "Фев", "Мар", "Апр", "Май", "Июн", "Июл", "Авг", "Сен", "Окт", "Ноя", "Дек");
    $l = array("Воскресенье", "Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота");
    $D = array("Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб");

    $format = str_replace("F", $F[date("n", $timestamp)], $format);
    $format = str_replace("M", $M[date("n", $timestamp)], $format);
    $format = str_replace("l", $l[date("w", $timestamp)], $format);
    $format = str_replace("D", $D[date("w", $timestamp)], $format);

    return date($format, $timestamp);
}
?>
<div class="news">
    <h1 class="headicon hicon_news">НОВОСТИ</h1>
    <div class="allnews">
        <?php $items = $this->getLatestNewsItems() ?>
        <?php foreach ($items as $item): ?>
            <section>
                <time>
                    <?php
                    $time = strtotime($item->getNewsTime());
                    echo rudate('d', $time);
                    echo "<span>".rudate(' F Y', $time)."</span>";
                    ?>
                </time>
                <p><?php echo Mage::helper('clnews')->contentFilter($item->getShortContent()) ?></p>
            </section>
        <?php endforeach; ?>
    </div>
    <a href="/clnews/" class="seeall">смотреть все</a>
</div>
