<div class="about">
    <h1 class="headicon hicon_about">О НАШЕМ МАГАЗИНЕ</h1>
    <p>Это пример текста о магазине, создан для того, чтобы было понятно, где будет текст. Это пример
        текста о магазине, создан для того, чтобы было понятно, где будет текст. Это пример текста о
        магазине, создан для того, чтобы было понятно, где будет текст. Это пример текста о магазине,
        создан для того, чтобы было понятно, где будет текст. Это пример текста о магазине, создан для
        того, чтобы было понятно, где будет текст. Это пример текста о магазине, создан для того, чтобы
        было понятно, где будет текст. <a href="#">подробнее</a></p>
    <div class="payment">
        <img src="img/dopay.png" alt="" />
        <a href="#">ОПЛАТА</a>
    </div>
    <div class="delivery">
        <img src="img/delivery.png" alt="" />
        <a href="#">ДОСТАВКА</a>
    </div>
</div>

<div class="newproduct">
    <div class="duablehead">
        <h1 class="headicon hicon_new">НОВИНИКИ</h1>
        <a href="#" class="seeall">смотреть все</a>
    </div>
    <div class="short_product">
        <section>
            <img src="img/product.jpg" alt="" class="product_img"/>
            <a href="#" class="product_head">Куртка женская зимняя</a>
            <p>7 600 <span>руб.</span></p>
            <a href="#" class="buy">
                <img src="img/buy.png" alt="">
                <span>КУПИТЬ</span>
            </a>
        </section>
        <section>
            <img src="img/product.jpg" alt="" class="product_img"/>
            <a href="#" class="product_head">Куртка женская зимняя</a>
            <p>7 600 <span>руб.</span></p>
            <a href="#" class="buy">
                <img src="img/buy.png" alt="">
                <span>КУПИТЬ</span>
            </a>
        </section>
        <section>
            <img src="img/product.jpg" alt="" class="product_img"/>
            <a href="#" class="product_head">Куртка женская зимняя</a>
            <p>7 600 <span>руб.</span></p>
            <a href="#" class="buy">
                <img src="img/buy.png" alt="">
                <span>КУПИТЬ</span>
            </a>
        </section>
        <section>
            <img src="img/product.jpg" alt="" class="product_img"/>
            <a href="#" class="product_head">Куртка женская зимняя</a>
            <p>7 600 <span>руб.</span></p>
            <a href="#" class="buy">
                <img src="img/buy.png" alt="">
                <span>КУПИТЬ</span>
            </a>
        </section>
        <section>
            <img src="img/product.jpg" alt="" class="product_img"/>
            <a href="#" class="product_head">Куртка женская зимняя</a>
            <p>7 600 <span>руб.</span></p>
            <a href="#" class="buy">
                <img src="img/buy.png" alt="">
                <span>КУПИТЬ</span>
            </a>
        </section>
        <section>
            <img src="img/product.jpg" alt="" class="product_img"/>
            <a href="#" class="product_head">Куртка женская зимняя</a>
            <p>7 600 <span>руб.</span></p>
            <a href="#" class="buy">
                <img src="img/buy.png" alt="">
                <span>КУПИТЬ</span>
            </a>
        </section>
    </div>
</div>

<div class="liders">
    <div class="duablehead">
        <h1 class="headicon hicon_lider">ЛИДЕРЫ ПРОДАЖ</h1>
        <a href="#" class="seeall">смотреть все</a>
    </div>
    <div class="short_product">
        <section>
            <img src="img/product.jpg" alt="" class="product_img"/>
            <a href="#" class="product_head">Куртка женская зимняя</a>
            <p>7 600 <span>руб.</span></p>
            <a href="#" class="buy">
                <img src="img/buy.png" alt="">
                <span>КУПИТЬ</span>
            </a>
        </section>
        <section>
            <img src="img/product.jpg" alt="" class="product_img"/>
            <a href="#" class="product_head">Куртка женская зимняя</a>
            <p>7 600 <span>руб.</span></p>
            <a href="#" class="buy">
                <img src="img/buy.png" alt="">
                <span>КУПИТЬ</span>
            </a>
        </section>
        <section>
            <img src="img/product.jpg" alt="" class="product_img"/>
            <a href="#" class="product_head">Куртка женская зимняя</a>
            <p>7 600 <span>руб.</span></p>
            <a href="#" class="buy">
                <img src="img/buy.png" alt="">
                <span>КУПИТЬ</span>
            </a>
        </section>
    </div>
</div>

<div class="sale">
    <div class="duablehead">
        <h1 class="headicon hicon_sale">СКИДКИ</h1>
        <a href="#" class="seeall">смотреть все</a>
    </div>
    <div class="short_product">
        <section>
            <img src="img/product.jpg" alt="" class="product_img"/>
            <a href="#" class="product_head">Куртка женская зимняя</a>
            <p>7 600 <span>руб.</span></p>
            <a href="#" class="buy">
                <img src="img/buy.png" alt="">
                <span>КУПИТЬ</span>
            </a>
        </section>
        <section>
            <img src="img/product.jpg" alt="" class="product_img"/>
            <a href="#" class="product_head">Куртка женская зимняя</a>
            <p>7 600 <span>руб.</span></p>
            <a href="#" class="buy">
                <img src="img/buy.png" alt="">
                <span>КУПИТЬ</span>
            </a>
        </section>
        <section>
            <img src="img/product.jpg" alt="" class="product_img"/>
            <a href="#" class="product_head">Куртка женская зимняя</a>
            <p>7 600 <span>руб.</span></p>
            <a href="#" class="buy">
                <img src="img/buy.png" alt="">
                <span>КУПИТЬ</span>
            </a>
        </section>
    </div>
</div>
<div class="index_text">
    <p class="left_text">
        Это пример текста о магазине, создан для того, чтобы было
        понятно, где будет текст. Это пример текста о магазине, создан
        для того, чтобы было понятно, где будет текст. Это пример текста
        о магазине, создан для того, чтобы было понятно, где будет текст.
        Это пример текста о магазине, создан для того, чтобы было
        понятно, где будет текст.
    </p>
    <p class="right_text">
        Это пример текста о магазине, создан для того, чтобы было
        понятно, где будет текст. Это пример текста о магазине, создан
        для того, чтобы было понятно, где будет текст. Это пример текста
        о магазине, создан для того, чтобы было понятно, где будет текст.
        Это пример текста о магазине, создан для того, чтобы было
        понятно, где будет текст.
    </p>
</div>

