<!DOCTYPE html>
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body>
<?php echo $this->getChildHtml('header') ?>
<div class="main">
    <div class="container">
        <div <?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
            <?php echo $this->getChildHtml('breadcrumbs') ?>
            <?php echo $this->getChildHtml('global_messages') ?>
            <?php echo $this->getChildHtml('content') ?>
        </div>
    </div>
</div>
<?php echo $this->getChildHtml('footer') ?>
</body>
</html>