<!DOCTYPE html>
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>

<body>
<?php echo $this->getChildHtml('after_body_start') ?>
<?php echo $this->getChildHtml('header') ?>
<div class="main">
    <div class="container">
        <aside>

            <?php if ($_leftContent = $this->getChildHtml('left_first')): ?>
                <div class=""><?php echo $_leftContent;   ?></div>
            <?php endif; ?>

<?php //echo $this->getChildHtml('left') ?>
            <menu>
                <ul>
                    <?php
                    $_categories = Mage::getModel('catalog/category')->getCollection()
                        ->addAttributeToSelect('name')
                        ->addAttributeToSelect('is_active')
                        ->addUrlRewriteToResult();
                    ?>

                    <?php foreach($_categories as $_category): ?>
                        <li>
                            <a href="<?php echo $_category->getUrl($_category); ?>">
                                <?php echo $_category->getName(); ?> (<?php echo $_category->getProductCount(); ?>)

                            </a>
                        </li>

                    <?php endforeach; ?>


                    <li><a href="#">Блузки (50)</a></li>
                    <li><a href="#">Боди (4)</a></li>
                    <li><a href="#">Туники (12)</a></li>
                    <li><a href="#">Платья (11)</a></li>
                    <li><a href="#">Брюки (32)</a></li>
                    <li><a href="#">Кофты (23)</a></li>
                    <li><a href="#">Шорты (2)</a></li>
                    <li><a href="#">Юбки (45)</a></li>
                    <li><a href="#">Пальто (22)</a></li>
                </ul>
            </menu>
        </aside>
        <article>
            <?php echo $this->getChildHtml('breadcrumbs') ?>
            <div <?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
                <?php echo $this->getChildHtml('global_messages') ?>
                <?php echo $this->getChildHtml('content') ?>
            </div>
        </article>
    </div>
</div>

<?php echo $this->getChildHtml('footer_before') ?>
<?php echo $this->getChildHtml('footer') ?>
<?php echo $this->getChildHtml('global_cookie_notice') ?>
<?php echo $this->getChildHtml('before_body_end') ?>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
