<!DOCTYPE html>
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>

<body>
<?php echo $this->getChildHtml('after_body_start') ?>
<?php echo $this->getChildHtml('header') ?>
<div class="main">
    <div class="container">
        <aside>

            <?php if ($_leftContent = $this->getChildHtml('left_first')): ?>
                <div class=""><?php echo $_leftContent;   ?></div>
            <?php endif; ?>

<?php //echo $this->getChildHtml('left') ?>



        </aside>
        <article>
            <?php echo $this->getChildHtml('breadcrumbs') ?>
            <div <?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
                <?php echo $this->getChildHtml('global_messages') ?>
                <?php echo $this->getChildHtml('content') ?>
            </div>
        </article>
    </div>
</div>

<?php echo $this->getChildHtml('footer_before') ?>
<?php echo $this->getChildHtml('footer') ?>
<?php echo $this->getChildHtml('global_cookie_notice') ?>
<?php echo $this->getChildHtml('before_body_end') ?>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
